from . import warehouse_skid
from . import order_line_tier
from . import product_margin
from . import stock_picking_extend
from . import stock_location_sequence
from . import stock_picking_workflow
from . import product_category_extend
from . import quality_capa
from . import quality_block
from . import dashboard_data
from . import warehouse_map
from . import res_partner_quality
from . import res_company
from . import purchase_sale_rating
from . import pos_config
from . import pos_product_alert
