from . import product_template
from . import product_product
from . import misc
from . import sale_order
from . import sale_order_wizard
from . import purchase_order
from . import master_data
from . import drug_substitution
from . import misc
